In [1]:
import numpy as np

data = [1, 2, 3, 4, 5]
arr = np.array(data)



In [2]:
arr

array([1, 2, 3, 4, 5])

[5 7 9]


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2
print(sum_arr)
is_greater = arr1 > arr2

[5 7 9]


In [97]:
sum_arr

array([5, 7, 9])

In [10]:
array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [11]:
array

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [19]:
np.linspace(100,1000,100)

array([ 100.        ,  100.9009009 ,  101.8018018 ,  102.7027027 ,
        103.6036036 ,  104.5045045 ,  105.40540541,  106.30630631,
        107.20720721,  108.10810811,  109.00900901,  109.90990991,
        110.81081081,  111.71171171,  112.61261261,  113.51351351,
        114.41441441,  115.31531532,  116.21621622,  117.11711712,
        118.01801802,  118.91891892,  119.81981982,  120.72072072,
        121.62162162,  122.52252252,  123.42342342,  124.32432432,
        125.22522523,  126.12612613,  127.02702703,  127.92792793,
        128.82882883,  129.72972973,  130.63063063,  131.53153153,
        132.43243243,  133.33333333,  134.23423423,  135.13513514,
        136.03603604,  136.93693694,  137.83783784,  138.73873874,
        139.63963964,  140.54054054,  141.44144144,  142.34234234,
        143.24324324,  144.14414414,  145.04504505,  145.94594595,
        146.84684685,  147.74774775,  148.64864865,  149.54954955,
        150.45045045,  151.35135135,  152.25225225,  153.15315

In [25]:
np.arange(5,15,3)

array([ 5,  8, 11, 14])

In [35]:

np.random.uniform(size = (3,3))

array([[0.16745177, 0.71492216, 0.97022469],
       [0.16136302, 0.36813668, 0.09630434],
       [0.06257932, 0.91243119, 0.54212501]])

In [61]:
np.random.randint(low=5, high=10, size=10)

array([8, 8, 6, 8, 9, 7, 6, 7, 6, 5])

In [64]:
np.random.random(5)

array([0.45437618, 0.33975412, 0.7836147 , 0.76294625, 0.17332914])

In [63]:
np.logspace(0,10,5,base=3)

array([1.00000000e+00, 1.55884573e+01, 2.43000000e+02, 3.78799512e+03,
       5.90490000e+04])

In [67]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
np.full((1,3),fill_value=4)

array([[4, 4, 4]])

In [73]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [75]:
arr = np.array([1,1,2,3,3,4,5,6,6,2])
np.max(arr)

6

In [79]:
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2], dtype=int64))

In [80]:
np.mean(arr,dtype='int')

3

In [81]:
a = np.array([-0.9, 0.5, 0.9,, 1 1.2, 1.4, 3.6, 4.7, 5.3])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4], dtype=int64)

In [91]:
A = np.random.randint(15,size=(3,5))

In [92]:
A

array([[ 8,  9,  2, 14,  6],
       [ 5,  5,  6,  5,  8],
       [13, 12,  0, 10,  4]])

In [96]:
A.reshape(5,3)

array([[ 8,  9,  2],
       [14,  6,  5],
       [ 5,  6,  5],
       [ 8, 13, 12],
       [ 0, 10,  4]])

In [105]:
def solve_n_queens(n):
  def backtrack(row):
    if row == n:
      return True  # All queens placed successfully

    for col in range(n):
      if is_safe(row, col):
        board[row][col] = 1
        if backtrack(row + 1):
          return True
        board[row][col] = 0  # Backtrack if placement doesn't lead to a solution

    return False  # No safe position found for this row

  # Function to check if a queen can be placed safely (consider diagonals)
  def is_safe(row, col):
    # ... implementation for checking diagonals and other positions

      board  = [[0] * n for _ in range(n)]  # Initialize empty board
  if solve_n_queens(0):
    print("Solution found:")
    # Print the board configuration
  else:
    print("No solution exists")


In [106]:
print("No solution exist")

No solution exist


In [104]:
print("Solution found")

Solution found


In [111]:
arr = np.array([ 8, 94,  9,  8, 99,  4,  9,  4, 9, 93, 93, 99])
np.expand_dims(arr,axis=0)

array([[ 8, 94,  9,  8, 99,  4,  9,  4,  9, 93, 93, 99]])

In [114]:
arr,axis=0

TypeError: cannot unpack non-iterable int object